# Generated by Django 5.2.6 on 2025-09-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    ]
